export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';
export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE';
export const CHANGE_FILTERED_VALUE = 'CHANGE_FILTERED_VALUE';
export const SET_FILTER = 'SET_FILTER';